/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Employee;
import model.EmployeeHistory;


/**
 *
 * @author parjita
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     * @param history
     */
    EmployeeHistory history;
    public String selectedImagePath;
    public CreateJPanel(EmployeeHistory history) {
        initComponents();
        this.history = history;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        TextEmployeeID = new javax.swing.JTextField();
        TextAge = new javax.swing.JTextField();
        TextGender = new javax.swing.JTextField();
        TextStartDate = new javax.swing.JTextField();
        TextLevel = new javax.swing.JTextField();
        TextTeamInfo = new javax.swing.JTextField();
        TextPositionTitle = new javax.swing.JTextField();
        TextCellPhoneNumber = new javax.swing.JTextField();
        TextEmailAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAddImage = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("EmployeeID :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Age : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Gender :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("StartDate:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Level:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("TeamInfo:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("PositionTitle");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("CellPhoneNumber");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("EmailAddress");

        TextName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextNameKeyReleased(evt);
            }
        });

        TextEmployeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextEmployeeIDKeyReleased(evt);
            }
        });

        TextAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAgeActionPerformed(evt);
            }
        });
        TextAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextAgeKeyReleased(evt);
            }
        });

        TextGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextGenderKeyReleased(evt);
            }
        });

        TextStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextStartDateKeyReleased(evt);
            }
        });

        TextLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextLevelKeyReleased(evt);
            }
        });

        TextTeamInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextTeamInfoKeyReleased(evt);
            }
        });

        TextPositionTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPositionTitleKeyReleased(evt);
            }
        });

        TextCellPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextCellPhoneNumberKeyReleased(evt);
            }
        });

        TextEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailAddressActionPerformed(evt);
            }
        });
        TextEmailAddress.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextEmailAddressPropertyChange(evt);
            }
        });
        TextEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextEmailAddressKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextEmailAddressKeyTyped(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAddImage.setText("Add Image");
        btnAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnAddImage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(TextCellPhoneNumber)
                            .addComponent(TextPositionTitle)
                            .addComponent(TextTeamInfo)
                            .addComponent(TextLevel)
                            .addComponent(TextStartDate)
                            .addComponent(TextGender)
                            .addComponent(TextAge)
                            .addComponent(TextEmployeeID)
                            .addComponent(TextName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 219, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextGender, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCellPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddImage, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAgeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
            // TODO add your handling code here:
               String Name =  TextName.getText();
               int EmployeeID = Integer.parseInt(TextEmployeeID.getText());
               int Age = Integer.parseInt(TextAge.getText());
               String Gender =  TextGender.getText();
               String StartDate =  TextStartDate.getText();
               String Level =  TextLevel.getText();
               String TeamInfo =  TextTeamInfo.getText();
               String PositionTitle =  TextPositionTitle.getText();
               double CellPhoneNumber = Double.parseDouble(TextCellPhoneNumber.getText());
               String EmailAddress =  TextEmailAddress.getText(); 
               
                            
               Employee em = history.addNewEmployee();
               em.setName(Name);
               em.setEmployeeID(EmployeeID);
               em.setAge(Age);
               em.setGender(Gender);
               em.setStartDate(StartDate);
               em.setLevel(Level);
               em.setTeamInfo(TeamInfo);
               em.setPositionTitle(PositionTitle);
               em.setCellPhoneNumber(CellPhoneNumber);
               em.setEmailAddress(EmailAddress);
               em.setProfilePath(selectedImagePath);
               
               JOptionPane.showMessageDialog(this,"New Employee Detail Added.");
               
               TextName.setText("");
               TextEmployeeID.setText("");
               TextAge.setText("");
               TextGender.setText("");
               TextStartDate.setText("");
               TextLevel.setText("");
               TextTeamInfo.setText("");
               TextPositionTitle.setText("");
               TextCellPhoneNumber.setText("");
               TextEmailAddress.setText("");             
                                         
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImageActionPerformed
        // TODO add your handling code here:
                JFileChooser browseImageFile = new JFileChooser();
                FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
                browseImageFile.addChoosableFileFilter(fnef);
                int showOpenDialogue = browseImageFile.showOpenDialog(null);         
                if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
                    File selectedImageFile = browseImageFile.getSelectedFile();
                    selectedImagePath = selectedImageFile.getAbsolutePath();
                }
    }//GEN-LAST:event_btnAddImageActionPerformed

    private void TextNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextName.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Username ");
            return;            
        }
    }//GEN-LAST:event_TextNameKeyReleased

    private void TextEmployeeIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextEmployeeIDKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextEmployeeID.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid EmployeeID ");
            return;            
        }
    }//GEN-LAST:event_TextEmployeeIDKeyReleased

    private void TextAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextAgeKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,3}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextAge.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Age ");
            return;            
        }
    }//GEN-LAST:event_TextAgeKeyReleased

    private void TextGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextGenderKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextGender.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Gender ");
            return;            
        }
    }//GEN-LAST:event_TextGenderKeyReleased

    private void TextStartDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextStartDateKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextStartDate.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid StartDat ");
            return;            
        }
    }//GEN-LAST:event_TextStartDateKeyReleased

    private void TextLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextLevelKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextLevel.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Level ");
            return;            
        }
    }//GEN-LAST:event_TextLevelKeyReleased

    private void TextTeamInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTeamInfoKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextTeamInfo.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Team Info ");
            return;            
        }
    }//GEN-LAST:event_TextTeamInfoKeyReleased

    private void TextPositionTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPositionTitleKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,100}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextPositionTitle.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Position Title ");
            return;            
        }
    }//GEN-LAST:event_TextPositionTitleKeyReleased

    private void TextCellPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCellPhoneNumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TextCellPhoneNumber.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid PhoneNumber ");
            return;            
        }
    }//GEN-LAST:event_TextCellPhoneNumberKeyReleased

    private void TextEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextEmailAddressKeyReleased
        // TODO add your handling code here:
          String PATTERN = "^[a-zA-Z0-9(.+)@(\\\\S+)]{0,40}$";
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match = patt.matcher(TextEmailAddress.getText());

            if(!match.matches()){            
                JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid EmailAdress ");
                return;            
            }
    }//GEN-LAST:event_TextEmailAddressKeyReleased

    private void TextEmailAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextEmailAddressKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextEmailAddressKeyTyped

    private void TextEmailAddressPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TextEmailAddressPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TextEmailAddressPropertyChange

    private void TextEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailAddressActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextAge;
    private javax.swing.JTextField TextCellPhoneNumber;
    private javax.swing.JTextField TextEmailAddress;
    private javax.swing.JTextField TextEmployeeID;
    private javax.swing.JTextField TextGender;
    private javax.swing.JTextField TextLevel;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextPositionTitle;
    private javax.swing.JTextField TextStartDate;
    private javax.swing.JTextField TextTeamInfo;
    private javax.swing.JButton btnAddImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

  
}
         
       
           

